name: Create single file Demo

on:
  push:
    branches: ["*"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm

      - run: npm ci

      - name: Build Library
        working-directory: Build
        run: npm run build

      - name: Demo
        working-directory: Demo
        run: npm run build:single

      - name: Rename for distribution
        working-directory: Demo/dist
        run: mv index.html UTAUjsEditor.html

      - name: Upload Demo Artifact
        uses: actions/upload-artifact@v4
        with:
          name: UTAUjsEditor-Standalone
          path: Demo/dist/UTAUjsEditor.html
          if-no-files-found: error
